### ISSUE TITLE
Flair Bot does not work

### ISSUE THREAD

**Issue by DrJuke** [TagPro-PreciousRoy/tagpro-flair-bot-django#11]
First time I tried, I linked my accounts, but the flairs would not click. The second time I tried, it wouldn't show me what to change my reserved name to.

**Comment by ylambda** [comment]
I was able to successfully change my flair just now.

Is this still an issue for you? Which browser are you using?

**Comment by TagPro-PreciousRoy** [comment]
I think this may have been fall-out from the bug I just fixed that was screwing up Reddit account names, so please try again. I will re-open if it's still happening for you.
